name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  generate-snake:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - name: Show generated files
        run: |
          echo "Generated files:"
          ls -la output/ || echo "Output directory not found"
          
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Commit and push Snake SVG
        run: |
          git add output/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🐍 Update snake animation SVG"
            git pull --rebase origin main
            git push
          fi
